# Generated by Django 4.2.18 on 2025-02-20 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_doctorprofile_user_alter_patientprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=models.CASCADE, to='accounts.User'),
    
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_table', to=settings.AUTH_USER_MODEL),
        ),
    ]
