# Generated by Django 4.2.19 on 2025-02-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_age_remove_user_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctorprofile',
            table='doctor_table',
        ),
        migrations.AlterModelTable(
            name='patientprofile',
            table='patient_table',
        ),
    ]
