# Generated by Django 5.1.6 on 2025-02-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctorprofile_table_alter_patientprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('PCOS Specialist', 'PCOS Specialist'), ('Infertility Specialist', 'Infertility Specialist'), ('Obstetrician', 'Obstetrician'), ('Menopause Specialist', 'Menopause Specialist'), ('Endometriosis Specialist', 'Endometriosis Specialist'), ('General Gynecologist', 'General Gynecologist')], default='General Gynecologist', max_length=100),
            preserve_default=False,
        ),
    ]
