# Generated by Django 5.1.6 on 2025-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_doctorprofile_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
