# Generated by Django 5.1.6 on 2025-02-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_patientprofile_table'),
        ('accounts', '0005_answer_upvote_count_question_upvote_count'),
    ]

    operations = [
    ]
