# Generated by Django 5.1.6 on 2025-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20250228_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='patientprofile',
            table='patient_table',
        ),
    ]
