# Generated by Django 4.2.18 on 2025-02-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_patientprofile_is_private_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='registration_number',
            field=models.CharField(default='Not Registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
