# Generated by Django 5.1.7 on 2025-03-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_answerlike_questionlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='availability',
            field=models.TextField(default=''),
        ),
    ]
