# Generated by Django 5.1.7 on 2025-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_doctorprofile_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='availability',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
