# Generated by Django 5.1.7 on 2025-03-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_doctorprofile_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='availability',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
