# Generated by Django 5.1.6 on 2025-04-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_doctorprofile_availability_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientprofile',
            table='accounts_patient_profile_table',
        ),
    ]
