# Generated by Django 5.1.6 on 2025-03-04 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gync', '0002_doctorfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorFeedback',
        ),
    ]
