# Generated by Django 4.2.18 on 2025-02-13 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gync', '0002_symptom_doctorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='symptoms_treated',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_pics/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='registration_no',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile_extra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='gync_appointments',
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(default='Unknown', max_length=255)),
                ('specialization', models.CharField(default='General', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='gync.doctor'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gync.doctor'),
        ),
    ]
