# Generated by Django 4.2.18 on 2025-02-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_doctorprofile_user_alter_patientprofile_user_and_more'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointments',
        ),
    ]
