# Generated by Django 5.1.6 on 2025-02-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='related_specialization',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
    ]
