# Generated by Django 5.1.6 on 2025-02-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_symptom_related_specialization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
