# Generated by Django 4.2.18 on 2025-02-13 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0003_delete_doctor_delete_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='xyz', max_length=255)),
                ('related_specialization', models.CharField(blank=True, default='General', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=5)),
                ('profile_picture', models.ImageField(blank=True, default='xyz', null=True, upload_to='patient_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_table',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=5)),
                ('user', models.OneToOneField(default='xyz', on_delete=django.db.models.deletion.CASCADE, related_name='patient_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
