# Generated by Django 4.2.19 on 2025-03-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SC", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="blog",
            table="SC_blog",
        ),
    ]
