# Generated by Django 5.1.5 on 2025-03-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SC', '0002_alter_blog_table'),
    ]

    operations = [
    ]
